import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ProviderStore from '../store/StoreProvider';
import '@/styles/globals.css';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Raspin",
  description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={poppins.className}>
			<body>
					<ProviderStore>{children}</ProviderStore>
			</body>
		</html>
	);
}
