export const ScraperConfig = {
  viewport: { width: 1366, height: 768 },
  navigationTimeout: 15_000,
  maxRetries: 3,
  delayRangeMs: [2000, 5000],
  blockedResources: [
    "doubleclick",
    "googlesyndication",
    "google-analytics",
    "criteo",
    "facebook",
    "analytics",
    "optimizely",
    "adsystem",
    "adservice",
    "tiktok",
    "snapchat",
    "akamai",
    "scorecardresearch",
    ".gif",
    ".jpg",
    ".png",
    "fonts.googleapis",
    "fontawesome",
    "cdn.jsdelivr",
    "shop.app",
  ],
};
